### PR TITLE
Updated to OpenSeadragon 2.1.0

### LINKED ISSUE #27: Controls don't work on iPhone
From @supercc: "I noticed the buttons + and - and home and the other one does not work when you open a image in the iPhone 5. Also the double tap to zoom in does not work. When I zoom in with the 2 fingers gesture, I can see little black squares blicking here and there while zooming on the pictures, still on the IPhone. I did not see this issue on the windows explorer."

I think the fix is just to upgrade OpenSeadragon; much better touch support in the recent version.

### PR DESCRIPTION
**Pull request by iangilman**
Fixes #27

### CODE REVIEW

**Comment by iangilman** [comment]
@gasi Can you merge and deploy?

**Comment by gasi** [comment]
@iangilman Sweet, thanks! Might be cool to use the `npm` one at some point but no biggie. We still manually have to push the images to CDN, but it looks like we’re set for now :+1:

**Comment by iangilman** [comment]
Yeah, I guess if we use the `npm` we'll need to add a build step to copy it into our `public` folder or something (as well as setting up something to push the images to the CDN when we update)?

**Comment by gasi** [comment]
> Yeah, I guess if we use the npm we'll need to add a build step to copy it into our public folder or something (as well as setting up something to push the images to the CDN when we update)?

Agreed. I am approaching ZoomHub from a more JIT point of view and will defer this until we actually see a need :smile:

**Comment by iangilman** [comment]
Good plan. :+1:

**Pull request merged**
