### PR TITLE
Allow new submissions through PostgreSQL storage

### PR DESCRIPTION
**Pull request by gasi**
Moving from SQLite to PostgreSQL should eliminate the biggest obstacle to accepting new content as SQLite only allows one write operation at a time due to file lock.

This PR also explores type-safe database queries using ~~[Opaleye](https://github.com/tomjaguarpaw/haskell-opaleye/)~~ [Squeal](https://github.com/morphismtech/squeal).

# TODO

#### Database: Read operations

- [x] `getById`: Get content by ID
- [x] `getById'`: Get content by ID (and increase view count based on sample rate)
- [x] `getByURL`: Get content by URL
- [x] `getByURL'`: Get content by URL (and increase view count based on sample rate)
- [x] `getNextUnprocessed`: Get oldest, most popular unprocessed content.
- [x] `getExpiredActive`: Get content that has been active for more than _x_ hours, say 24h.

#### Write operations

- [x] `create`: Create content from URL (setting `type = Unknown`, `state = Initialized`, `initializedAt = currentTime`.
- [x] `dequeueNextUnprocessed`: Pick content with `state = Initialized` based on highest view count (preferring more popular content) and then oldest date (preferring content submitted earlier.)
- [x] `markAsActive`: Set `state = Active` + `active_at`.
- [x] `markAsFailure`: Set `state = CompletedFailure`, etc.
- [x] `markAsSuccess`: Set `state = CompletedSuccess`, etc.
- [x] `resetAsInitialized`: Set `state = Initialized`.

#### Other

- [x] Switch API from SQLite to Squeal
- [x] Switch Worker from SQLite to Squeal

## Test

- [x] Add tests for Squeal based API
- [ ] ~~Add tests for worker (?)~~

### CI

- [x] Update CircleCI configuration to work with PostgreSQL

### PostgresQL

- [x] Set up PostgreSQL databased based on Squeal schema and `setup` function.
- ~~[ ] Set up scripts for hourly / daily / weekly PostgreSQL backups: https://wiki.postgresql.org/wiki/Automated_Backup_on_Linux~~ Use AWS RDS instance
- [x] Set up trigger for generating hash IDs after insertion (avoids complicated and inefficient mechanics in application code). References:
    - PostgreSQL + V8/JS implementation: https://blog.abevoelker.com/2017-01-03/generating-youtube-like-ids-in-postgres-using-plv8-and-hashids/
    - SQL only implementation: https://github.com/andreystepanov/hashids.sql
    - Short IDs using `pgcrypto`: https://blog.andyet.com/2016/02/23/generating-shortids-in-postgres/
    - ‘Official’ C implementation (non-portable, e.g. AWS RDS): https://hashids.org/postgresql/
- [x] Create script to import SQLite data into PostgreSQL
- [x] Pull latest SQLite backup
- ~~[ ] Import SQLite into PostgreSQL on staging server~~
- [x] Import SQLite into PostgreSQL on production server

### CircleCI

- ~~[ ] Run migrations from CircleCI~~ Run migrations before app start.

### Staging

- [x] Set up new staging PostgreSQL server
- [x] Get everything running on new staging server
- [x] Test everything on new staging server

### Production
- [x] Set up new production PostgreSQL server
- [x] Test everything on new production server
- [x] Upload latest data to production PostgreSQL database
- [ ] Cut over traffic 🎉

### CODE REVIEW

**Comment by iangilman** [comment]
Sounds great!

**Comment by iangilman** [comment]
Exciting to see some action here!

**Comment by iangilman** [comment]
Great to see new action on this front! :-)

**Comment by gasi** [comment]
@iangilman Thanks for the encouragement — it means a lot! Quite dismayed this PR has been open for almost three years 😞

**Comment by thomasmarsh** [comment]
Getting close!

**Pull request merged**
